//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AromaticCafe  
{
    using System;
    using System.Collections.Generic;
    
    public partial class Order  //таблица Order
    {
        public int OrderId { get; set; }
        public int UserId { get; set; }
        public string OrderContent { get; set; }
    
        public virtual User Users { get; set; }
    }
}
